name: Sync with Upstream
on:
  schedule:
    - cron: '* */12 * * *' # Schedule the workflow to run every 12 hours
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch upstream changes
        run: git fetch upstream
      - name: Merge upstream changes
        run: git merge upstream/master
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
